<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from org.project60.sepa/xml/schema/CRM/Sepa/Mandate.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:bdc8f136f6b134cbb2b643a767d4e78a)
 */

/**
 * Database access object for the SEPAMandate entity.
 */
class CRM_Sepa_DAO_SEPAMandate extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_sdd_mandate';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * ID
   *
   * @var int
   */
  public $id;

  /**
   * A unique mandate reference
   *
   * @var string
   */
  public $reference;

  /**
   * Information about the source of registration of the mandate
   *
   * @var string
   */
  public $source;

  /**
   * Physical tablename for the contract entity being joined, eg contributionRecur or Membership
   *
   * @var string
   */
  public $entity_table;

  /**
   * FK to contract entity table specified in entity_table column.
   *
   * @var int
   */
  public $entity_id;

  /**
   * by default now()
   *
   * @var datetime
   */
  public $date;

  /**
   * FK to ssd_creditor
   *
   * @var int
   */
  public $creditor_id;

  /**
   * FK to Contact ID of the debtor
   *
   * @var int
   */
  public $contact_id;

  /**
   * Name of the account holder
   *
   * @var string
   */
  public $account_holder;

  /**
   * Iban of the debtor
   *
   * @var string
   */
  public $iban;

  /**
   * BIC of the debtor
   *
   * @var string
   */
  public $bic;

  /**
   * RCUR for recurrent (default), OOFF for one-shot
   *
   * @var string
   */
  public $type;

  /**
   * Status of the mandate (INIT, OOFF, FRST, RCUR, SENT, INVALID, COMPLETE, ONHOLD)
   *
   * @var string
   */
  public $status;

  /**
   * @var datetime
   */
  public $creation_date;

  /**
   * FK to civicrm_contribution
   *
   * @var int
   */
  public $first_contribution_id;

  /**
   * @var datetime
   */
  public $validation_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_sdd_mandate';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'creditor_id', 'civicrm_sdd_creditor', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'first_contribution_id', 'civicrm_contribution', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Dynamic(self::getTableName(), 'entity_id', NULL, 'id', 'entity_table');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Sepa_ExtensionUtil::ts('ID'),
          'required' => TRUE,
          'where' => 'civicrm_sdd_mandate.id',
          'export' => TRUE,
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'reference' => [
          'name' => 'reference',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Sepa_ExtensionUtil::ts('Reference'),
          'description' => CRM_Sepa_ExtensionUtil::ts('A unique mandate reference'),
          'required' => TRUE,
          'maxlength' => 35,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_sdd_mandate.reference',
          'export' => TRUE,
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'source' => [
          'name' => 'source',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Sepa_ExtensionUtil::ts('Source'),
          'description' => CRM_Sepa_ExtensionUtil::ts('Information about the source of registration of the mandate'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_sdd_mandate.source',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Sepa_ExtensionUtil::ts('Entity Table'),
          'description' => CRM_Sepa_ExtensionUtil::ts('Physical tablename for the contract entity being joined, eg contributionRecur or Membership'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_sdd_mandate.entity_table',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Sepa_ExtensionUtil::ts('Entity ID'),
          'description' => CRM_Sepa_ExtensionUtil::ts('FK to contract entity table specified in entity_table column.'),
          'required' => TRUE,
          'where' => 'civicrm_sdd_mandate.entity_id',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'date' => [
          'name' => 'date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => CRM_Sepa_ExtensionUtil::ts('Mandate signature date'),
          'description' => CRM_Sepa_ExtensionUtil::ts('by default now()'),
          'required' => TRUE,
          'where' => 'civicrm_sdd_mandate.date',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'creditor_id' => [
          'name' => 'creditor_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Sepa_ExtensionUtil::ts('Creditor ID'),
          'description' => CRM_Sepa_ExtensionUtil::ts('FK to ssd_creditor'),
          'where' => 'civicrm_sdd_mandate.creditor_id',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
          'FKClassName' => 'CRM_Sepa_DAO_SEPACreditor',
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Sepa_ExtensionUtil::ts('Contact ID'),
          'description' => CRM_Sepa_ExtensionUtil::ts('FK to Contact ID of the debtor'),
          'where' => 'civicrm_sdd_mandate.contact_id',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
        ],
        'account_holder' => [
          'name' => 'account_holder',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Sepa_ExtensionUtil::ts('Account Holder'),
          'description' => CRM_Sepa_ExtensionUtil::ts('Name of the account holder'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_sdd_mandate.account_holder',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'iban' => [
          'name' => 'iban',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Sepa_ExtensionUtil::ts('Iban'),
          'description' => CRM_Sepa_ExtensionUtil::ts('Iban of the debtor'),
          'required' => FALSE,
          'maxlength' => 42,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_sdd_mandate.iban',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'bic' => [
          'name' => 'bic',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Sepa_ExtensionUtil::ts('Bic'),
          'description' => CRM_Sepa_ExtensionUtil::ts('BIC of the debtor'),
          'maxlength' => 11,
          'size' => CRM_Utils_Type::TWELVE,
          'where' => 'civicrm_sdd_mandate.bic',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'type' => [
          'name' => 'type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Sepa_ExtensionUtil::ts('Type'),
          'description' => CRM_Sepa_ExtensionUtil::ts('RCUR for recurrent (default), OOFF for one-shot'),
          'required' => TRUE,
          'maxlength' => 4,
          'size' => CRM_Utils_Type::FOUR,
          'where' => 'civicrm_sdd_mandate.type',
          'default' => 'RCUR',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Sepa_ExtensionUtil::ts('Status'),
          'description' => CRM_Sepa_ExtensionUtil::ts('Status of the mandate (INIT, OOFF, FRST, RCUR, SENT, INVALID, COMPLETE, ONHOLD)'),
          'required' => TRUE,
          'maxlength' => 8,
          'size' => CRM_Utils_Type::EIGHT,
          'where' => 'civicrm_sdd_mandate.status',
          'default' => 'INIT',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'creation_date' => [
          'name' => 'creation_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => CRM_Sepa_ExtensionUtil::ts('creation date'),
          'where' => 'civicrm_sdd_mandate.creation_date',
          'export' => TRUE,
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
        'first_contribution_id' => [
          'name' => 'first_contribution_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Sepa_ExtensionUtil::ts('First Contribution (to be deprecated)'),
          'description' => CRM_Sepa_ExtensionUtil::ts('FK to civicrm_contribution'),
          'where' => 'civicrm_sdd_mandate.first_contribution_id',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contribute_DAO_Contribution',
        ],
        'validation_date' => [
          'name' => 'validation_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => CRM_Sepa_ExtensionUtil::ts('validation date'),
          'where' => 'civicrm_sdd_mandate.validation_date',
          'table_name' => 'civicrm_sdd_mandate',
          'entity' => 'SEPAMandate',
          'bao' => 'CRM_Sepa_DAO_SEPAMandate',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'sdd_mandate', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'sdd_mandate', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'reference' => [
        'name' => 'reference',
        'field' => [
          0 => 'reference',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_sdd_mandate::1::reference',
      ],
      'index_entity' => [
        'name' => 'index_entity',
        'field' => [
          0 => 'entity_table',
          1 => 'entity_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_mandate::0::entity_table::entity_id',
      ],
      'iban' => [
        'name' => 'iban',
        'field' => [
          0 => 'iban',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_mandate::0::iban',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
