<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from org.project60.sepa/xml/schema/CRM/Sepa/MandateLink.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:9614b54bd626b0f364867d63ffcbd305)
 */
use CRM_Sepa_ExtensionUtil as E;

/**
 * Database access object for the SepaMandateLink entity.
 */
class CRM_Sepa_DAO_SepaMandateLink extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_sdd_entity_mandate';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique SepaMandateLink ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to SepaMandate
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $mandate_id;

  /**
   * Physical table name for entity being linked, eg civicrm_membership
   *
   * @var string
   *   (SQL type: varchar(64))
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_table;

  /**
   * FK to entity table specified in entity_table column
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_id;

  /**
   * Link class, freely defined by client
   *
   * @var string|null
   *   (SQL type: varchar(16))
   *   Note that values will be retrieved from the database as a string.
   */
  public $class;

  /**
   * Is this link still active?
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_active;

  /**
   * Link creation date (default now())
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $creation_date;

  /**
   * Start date of the link (optional)
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $start_date;

  /**
   * End date of the link (optional)
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $end_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_sdd_entity_mandate';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Sepa Mandate Links') : E::ts('Sepa Mandate Link');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique SepaMandateLink ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sdd_entity_mandate.id',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
          'FKClassName' => 'CRM_Sepa_DAO_SEPAMandate',
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'mandate_id' => [
          'name' => 'mandate_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('SepaMandate ID'),
          'description' => E::ts('FK to SepaMandate'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sdd_entity_mandate.mandate_id',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
          'html' => [
            'type' => 'EntityRef',
          ],
          'add' => NULL,
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Entity Table'),
          'description' => E::ts('Physical table name for entity being linked, eg civicrm_membership'),
          'required' => TRUE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sdd_entity_mandate.entity_table',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
          'add' => NULL,
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Entity ID'),
          'description' => E::ts('FK to entity table specified in entity_table column'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sdd_entity_mandate.entity_id',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
          'DFKEntityColumn' => 'entity_table',
          'FKColumnName' => 'id',
          'add' => NULL,
        ],
        'class' => [
          'name' => 'class',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Link Class'),
          'description' => E::ts('Link class, freely defined by client'),
          'maxlength' => 16,
          'size' => CRM_Utils_Type::TWELVE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sdd_entity_mandate.class',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Active?'),
          'description' => E::ts('Is this link still active?'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sdd_entity_mandate.is_active',
          'default' => '1',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
          'add' => NULL,
        ],
        'creation_date' => [
          'name' => 'creation_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Creation Date'),
          'description' => E::ts('Link creation date (default now())'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sdd_entity_mandate.creation_date',
          'default' => 'now()',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'start_date' => [
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Start Date'),
          'description' => E::ts('Start date of the link (optional)'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sdd_entity_mandate.start_date',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'end_date' => [
          'name' => 'end_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('End Date'),
          'description' => E::ts('End date of the link (optional)'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sdd_entity_mandate.end_date',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'sdd_entity_mandate', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'sdd_entity_mandate', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'link' => [
        'name' => 'link',
        'field' => [
          0 => 'entity_table',
          1 => 'entity_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_entity_mandate::0::entity_table::entity_id',
      ],
      'class' => [
        'name' => 'class',
        'field' => [
          0 => 'class',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_entity_mandate::0::class',
      ],
      'is_active' => [
        'name' => 'is_active',
        'field' => [
          0 => 'is_active',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_entity_mandate::0::is_active',
      ],
      'start_date' => [
        'name' => 'start_date',
        'field' => [
          0 => 'start_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_entity_mandate::0::start_date',
      ],
      'end_date' => [
        'name' => 'end_date',
        'field' => [
          0 => 'end_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_entity_mandate::0::end_date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
