<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.6                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2015                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2015
 *
 * Generated from xml/schema/CRM/Sepa/SEPAMandateFileRow.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
class CRM_Sepa_DAO_SEPAMandateFileRow extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   */
  static $_tableName = 'civicrm_sdd_mandate_file_row';
  /**
   * static instance to hold the field values
   *
   * @var array
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   *
   * @var int unsigned
   */
  public $mandate_file_id;
  /**
   *
   * @var int unsigned
   */
  public $mandate_id;
  /**
   * DateTime when creditor responsed to uploaded file with mandates.
   *
   * @var datetime
   */
  public $response_date;
  /**
   * Filename from creditor
   *
   * @var string
   */
  public $response_filename;
  /**
   * Status response
   *
   * @var string
   */
  public $response_status;
  /**
   * Optional response comment
   *
   * @var string
   */
  public $response_comment;
  /**
   * class constructor
   *
   * @return civicrm_sdd_mandate_file_row
   */
  function __construct()
  {
    $this->__table = 'civicrm_sdd_mandate_file_row';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  static function getReferenceColumns()
  {
    if (!self::$_links) {
      self::$_links = static ::createReferenceColumns(__CLASS__);
      self::$_links[] = new CRM_Core_Reference_Basic(self::getTableName() , 'mandate_file_id', 'civicrm_sdd_mandate_file', 'id');
      self::$_links[] = new CRM_Core_Reference_Basic(self::getTableName() , 'mandate_id', 'civicrm_sdd_mandate', 'id');
    }
    return self::$_links;
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('ID'),
          'description' => 'ID',
          'required' => true,
          'export' => true,
          'where' => 'civicrm_sdd_mandate_file_row.id',
          'headerPattern' => '',
          'dataPattern' => '',
        ) ,
        'mandate_file_id' => array(
          'name' => 'mandate_file_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Mandate file ID'),
          'description' => 'Mandate file ID',
          'required' => true,
          'export' => true,
          'where' => 'civicrm_sdd_mandate_file_row.mandate_file_id',
          'headerPattern' => '',
          'dataPattern' => '',
          'FKClassName' => 'CRM_Sepa_DAO_SEPAMandateFile',
        ) ,
        'mandate_id' => array(
          'name' => 'mandate_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Mandate ID'),
          'description' => 'Mandate ID',
          'required' => true,
          'export' => true,
          'where' => 'civicrm_sdd_mandate_file_row.mandate_id',
          'headerPattern' => '',
          'dataPattern' => '',
          'FKClassName' => 'CRM_Sepa_DAO_SEPAMandate',
        ) ,
        'response_date' => array(
          'name' => 'response_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Response Date') ,
          'description' => 'DateTime when creditor responsed to uploaded file with mandates.',
          'required' => false,
          'export' => true,
          'where' => 'civicrm_sdd_mandate_file_row.response_date',
          'headerPattern' => '',
          'dataPattern' => '',
        ) ,
        'response_filename' => array(
          'name' => 'response_filename',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Response filename') ,
          'description' => 'Filename from creditor',
          'required' => false,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'export' => true,
          'where' => 'civicrm_sdd_mandate_file_row.response_filename',
          'headerPattern' => '',
          'dataPattern' => '',
        ) ,
        'response_status' => array(
          'name' => 'response_status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Response status') ,
          'description' => 'Status response',
          'required' => false,
          'maxlength' => 10,
          'size' => CRM_Utils_Type::TWELVE,
          'export' => true,
          'where' => 'civicrm_sdd_mandate_file_row.response_status',
          'headerPattern' => '',
          'dataPattern' => '',
        ) ,
        'response_comment' => array(
          'name' => 'response_comment',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Response comment') ,
          'description' => 'Optional response comment',
          'required' => false,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'export' => true,
          'where' => 'civicrm_sdd_mandate_file_row.response_comment',
          'headerPattern' => '',
          'dataPattern' => '',
        ) ,
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'mandate_file_id' => 'mandate_file_id',
        'mandate_id' => 'mandate_id',
        'response_date' => 'response_date',
        'response_filename' => 'response_filename',
        'response_status' => 'response_status',
        'response_comment' => 'response_comment',
      );
    }
    return self::$_fieldKeys;
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['sdd_mandate_file_row'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['sdd_mandate_file_row'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}
