    <PmtInf>
      <PmtInfId>{$group.reference}</PmtInfId>
      <PmtMtd>DD</PmtMtd>
      <PmtTpInf>
        <SvcLvl>
          <Prtry>CHTA</Prtry>
        </SvcLvl>
        <LclInstrm>
          <Prtry>LSV+</Prtry>
        </LclInstrm>
      </PmtTpInf>
      <ReqdColltnDt>{$group.collection_date|crmDate:"%Y-%m-%d"}</ReqdColltnDt>
      <Cdtr>
        <Nm>{$creditor.name}</Nm>
        <PstlAdr>
          <Ctry>CH</Ctry>
          <AdrLine>{$creditor.address}</AdrLine>
        </PstlAdr>
      </Cdtr>
      <CdtrAcct>
        <Id>
          <IBAN>{$creditor.iban}</IBAN>
        </Id>
      </CdtrAcct>
      <CdtrAgt>
        <FinInstnId>
          <ClrSysMmbId>
            <MmbId>{$creditor.iid}</MmbId>
          </ClrSysMmbId>
          <Othr>
            <Id>{$creditor.esr_teilnehmernummer}</Id>
          </Othr>
        </FinInstnId>
      </CdtrAgt>
      <CdtrSchmeId>
        <Id>
          <PrvtId>
            <Othr>
              <Id>{$creditor.lsv_id}</Id>
              <SchmeNm>
                <Prtry>CHLS</Prtry>
              </SchmeNm>
            </Othr>
          </PrvtId>
        </Id>
      </CdtrSchmeId>
{foreach from=$contributions item="contribution"}
      <DrctDbtTxInf>
        <PmtId>
          <InstrId>INSTRID-{$contribution.end2endID}</InstrId>
          <EndToEndId>{$contribution.end2endID}</EndToEndId>
        </PmtId>
        <InstdAmt Ccy="CHF">{$contribution.total_amount}</InstdAmt>
        <DbtrAgt>
          <FinInstnId>
            <ClrSysMmbId>
              <MmbId>{$contribution.iid}</MmbId>
            </ClrSysMmbId>
          </FinInstnId>
        </DbtrAgt>
        <Dbtr>
          <Nm>{$contribution.display_name}</Nm>
          <PstlAdr>
            <Ctry>{$contribution.ctry}</Ctry>
            <AdrLine>{$contribution.street_address}</AdrLine>
            <AdrLine>{$contribution.postal_code} {$contribution.city}</AdrLine>
          </PstlAdr>
        </Dbtr>
        <DbtrAcct>
          <Id>
            <IBAN>{$contribution.iban}</IBAN>
          </Id>
        </DbtrAcct>
        <RmtInf>
          <Ustrd>{$contribution.message}</Ustrd>
          <Strd>
            <CdtrRefInf>
              <Tp>
                <CdOrPrtry>
                  <Prtry>ESR</Prtry>
                </CdOrPrtry>
              </Tp>
              <Ref>{$contribution.esr}</Ref>
            </CdtrRefInf>
          </Strd>
        </RmtInf>
      </DrctDbtTxInf>
{/foreach}
    </PmtInf>
