name: PHPUnit

permissions: {}

on:
  workflow_dispatch:
    inputs:
      civicrm-version:
        description: 'CiviCRM version constraint'
        required: false
        type: string
  pull_request:
    paths:
      - '**.php'
      - composer.json
      - tools/phpunit/composer.json
      - phpunit.xml.dist
      - .github/workflows/phpunit.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.civicrm-version }}
  cancel-in-progress: true

jobs:
  phpunit:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.5']
        prefer: ['prefer-stable', 'prefer-lowest']
        experimental: [false]
        include:
          - php-versions: 8.6
            prefer: prefer-source
            experimental: true
    name: PHPUnit with PHP ${{ matrix.php-versions }} ${{ matrix.prefer }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: bcmath, curl, fileinfo, gd, intl, mbstring, mysqli, xml, zip
          coverage: pcov
        env:
          fail-fast: true

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.prefer }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.prefer }}-

      - name: Set up MySQL
        run: |
          # MySQL is installed by default.
          # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#mysql
          sudo systemctl start mysql.service
          until sudo mysqladmin ping --silent; do sleep 1; done
          sudo mysql -e 'CREATE DATABASE civicrm;' --user=root --password=root
          sudo mysql -e 'CREATE USER "user"@"localhost" IDENTIFIED BY "password";' --user=root --password=root
          sudo mysql -e 'GRANT ALL ON *.* TO "user"@"localhost";' --user=root --password=root
          sudo mysql -e 'GRANT SUPER ON *.* TO "user"@"localhost";' --user=root --password=root
          sudo mysql -e 'FLUSH PRIVILEGES;' --user=root --password=root

      - name: Install dependencies
        env:
          COMPOSER_COMPILE: all
          INPUTS_CIVICRM_VERSION: ${{ inputs.civicrm-version }}
          MATRIX_EXPERIMENTAL: ${{ matrix.experimental }}
          MATRIX_PREFER: ${{ matrix.prefer }}
        run: |
          if [ "${MATRIX_PREFER}" = "prefer-lowest" ]; then
            # Actually test with lowest possible versions.
            export COMPOSER_NO_BLOCKING=1
          fi

          # Prevent this git error: The repository does not have the correct ownership and git refuses to use it
          git config --global --add safe.directory "$PWD"

          EXT_DIR=$PWD
          EXT_COMPOSER_NAME=$(composer show --self --name-only)
          composer composer-phpunit -- update --no-progress --optimize-autoloader
          cd ..
          git clone https://github.com/civicrm/civicrm-standalone.git
          cd civicrm-standalone

          if [ "${MATRIX_EXPERIMENTAL}" == "true" ]; then
            sed -E -i composer.json \
              -e 's/"minimum-stability":[^,]*/"minimum-stability": "dev"/' \
              -e 's/"prefer-stable":[^,]*/"prefer-stable": false/'
            # Ignore upper bound of php requirement to test with development
            # version of PHP, even if not allowed by some composer.json.
            export COMPOSER_IGNORE_PLATFORM_REQ="php+"
          fi

          composer config --no-plugins allow-plugins.composer/installers true
          composer config --no-plugins allow-plugins.cweagans/composer-patches true
          composer config --json 'extra.installer-paths.ext/{$name}' '["type:civicrm-ext"]'
          composer config repositories.test path $EXT_DIR

          # Use civicrm-core and civicrm-packages defined in extension's composer.json.
          composer remove --no-update civicrm/civicrm-core civicrm/civicrm-packages
          composer require --no-progress composer/installers civicrm/cli-tools
          if [ -n "${INPUTS_CIVICRM_VERSION}" ]; then
            composer require --no-update "civicrm/civicrm-core:${INPUTS_CIVICRM_VERSION}" \
              "civicrm/civicrm-packages:${INPUTS_CIVICRM_VERSION}"
          fi

          # Install dev dependencies from extension's composer.json.
          jq -r '.["require-dev"] | to_entries[] | "\"\(.key):\(.value)\""' "$EXT_DIR/composer.json" 2>/dev/null | xargs -r composer require --dev --no-update

          # --with-all-dependencies is required because downgrades from packages
          # installed before might be necessary.
          # civicrm/composer-compile-plugin v0.22 is the minimum version
          # compatible with symfony/console >=8.0 used in composer since 2.9.0.
          composer require --with-all-dependencies --no-progress --${MATRIX_PREFER} \
            --optimize-autoloader $EXT_COMPOSER_NAME 'civicrm/composer-compile-plugin:>=0.22'

      - name: Set up CiviCRM
        env:
          # Comma-separated list of CiviCRM components to enable, e.g.
          # CiviEvent,CiviContribute. Components are mapped to extensions. If
          # empty, all components are enabled. Enabling the dependent extensions
          # should be actually triggered in the test class. Not enabling any
          # component isn't possible.
          CIVICRM_COMPONENTS: "CiviReport"
          DATABASE_URL: mysql://user:password@127.0.0.1:3306/civicrm?new_link=true
        run: |
          cd ../civicrm-standalone
          export PATH="$(realpath vendor/bin):$PATH"
          cv core:install --db="$DATABASE_URL" --comp="$CIVICRM_COMPONENTS"
          export CV_CONFIG="$HOME/.cv.json"
          cv vars:fill --quiet
          sed -i "s#\"TEST_DB_DSN\": \".*\"#\"TEST_DB_DSN\": \"$DATABASE_URL\"#g" "$CV_CONFIG"

      - name: Setup problem matchers for PHP
        env:
          RUNNER_TOOL_CACHE: ${{ runner.tool_cache }}
        run: echo "::add-matcher::${RUNNER_TOOL_CACHE}/php.json"

      - name: Setup problem matchers for PHPUnit
        env:
          RUNNER_TOOL_CACHE: ${{ runner.tool_cache }}
        run: echo "::add-matcher::${RUNNER_TOOL_CACHE}/phpunit.json"

      - name: Run PHPUnit
        run: |
          export PATH="$(realpath ../civicrm-standalone/vendor/bin):$PATH"
          export CV_CONFIG="$HOME/.cv.json"
          cd ../civicrm-standalone/ext/$(basename "$PWD")
          composer phpunit
